FROM nginx:alpine
COPY index.html /usr/share/nginx/html/index.html
COPY auth.html /usr/share/nginx/html/auth.html
COPY client-profile.html /usr/share/nginx/html/client-profile.html
COPY master-profile.html /usr/share/nginx/html/master-profile.html
COPY admin-profile.html /usr/share/nginx/html/admin-profile.html
EXPOSE 80
